### ISSUE TITLE
能否增加两步验证码，保证账户安全性

### ISSUE THREAD

**Issue by hlf20010508** [yanglbme/cordcloud-action#4]
我前几天发现我的账户泄漏了，我增加了两步验证码，然后这个action就用不了了。
我查看了代码，发现在`app/action.py`是支持两步验证码的。
不知道为什么你没有实装。
我认为可以通过让用户将两步验证码的绑定码放到`github secret`中，然后使用`pyotp`让`action`能够生成两步验证码，从而登录。

具体代码如下：
```py
import pyotp
code = pyotp.TOTP("XXXXXXXXXXXXXXXX")
code.now()
```

`code.now()`就是登录所需要的两步验证码。

我已`fork`了你的仓库，但我发现我不会`github action`的代码，而两步验证码的代码就这几行，不复杂，所以就提这个`issue`希望你能实现一下。

**Comment by hlf20010508** [comment]
可以同时支持有两步验证码和没有两步验证码这两种模式。
判断一下环境变量里有没有`secrets.CC_CODE`就可以了。

**Comment by yanglbme** [comment]
感谢反馈，我待会有空看一下。如果确定可以的话，今天就加上

**Comment by yanglbme** [comment]
@hlf20010508 

已经支持了，在 .yml 中配置多一个 secret 参数：

```yml
name: CordCloud

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: yanglbme/cordcloud-action@main
        with:
          email: ${{ secrets.CC_EMAIL }}
          passwd: ${{ secrets.CC_PASSWD }}
          secret: ${{ secrets.CC_SECRET }}
```

然后在 Settings 中修改 action 的 secrets，增加一个 `CC_SECRET` 配置
